apiVersion: v1
kind: Service
metadata:
  name: sampleprojectreact-service
spec:
  type: NodePort
  selector:
    app: sampleprojectreact
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
